name: Run Main Script

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes

jobs:
  run-main:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run main script
      run: python main.py 